name: monsieurcaca
favicon: null
layout_spectrum: 0.1600021931808442
typography_spectrum: 0.756855946034193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07107840152457356
  lightness: 0.6984052038751543
  saturation: 0.07735055265948176
  rhythmicContrast: 0.7549754567444324
purpose: []
